#ifndef CADICAL_BUILD_HPP_INCLUDED
#define CADICAL_BUILD_HPP_INCLUDED

// This file is normally autogenerated by CaDiCaL's build system.
// For EvalMaxSAT2022 we ship a static, reproducible version so version.cpp builds
// on all platforms and CaDiCaL::version() symbols are always present.

#define VERSION "b783a33"  // arbitrary, human readable; not used for ABI
#define IDENTIFIER "b783a33930e809df46b8baf76ffd0c1b826137b5"

// Keep these as plain strings. CaDiCaL prints them; nothing should depend on exact values.
#define COMPILER "unknown"
#define FLAGS "-Wall -Wextra -O3 -DNDEBUG"
#define DATE "unknown"

//
// Some CaDiCaL snapshots reference slightly different macro names.
// Provide compatible aliases.
//
#define CFLAGS FLAGS
#define CXXFLAGS FLAGS

#endif
