/home/josalhor/Desktop/wbo-py/open-wbo/Encoder.o /home/josalhor/Desktop/wbo-py/open-wbo/Encoder.or /home/josalhor/Desktop/wbo-py/open-wbo/Encoder.od /home/josalhor/Desktop/wbo-py/open-wbo/Encoder.op: /home/josalhor/Desktop/wbo-py/open-wbo/Encoder.cc \
 /home/josalhor/Desktop/wbo-py/open-wbo/Encoder.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/core/Solver.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Heap.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Vec.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/IntTypes.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/XAlloc.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Alg.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/utils/Options.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/utils/ParseUtils.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/core/SolverTypes.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Map.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Alloc.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/core/BoundedQueue.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/core/Constants.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Clone.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/core/SolverStats.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/MaxTypes.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/encodings/Enc_CNetworks.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/encodings/Encodings.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/encodings/../MaxTypes.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/encodings/Enc_GTE.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/encodings/Enc_Ladder.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/encodings/Enc_MTotalizer.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/encodings/Enc_SWC.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/encodings/Enc_Totalizer.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/encodings/Enc_Adder.h
/home/josalhor/Desktop/wbo-py/open-wbo/Main.o /home/josalhor/Desktop/wbo-py/open-wbo/Main.or /home/josalhor/Desktop/wbo-py/open-wbo/Main.od /home/josalhor/Desktop/wbo-py/open-wbo/Main.op: /home/josalhor/Desktop/wbo-py/open-wbo/Main.cc \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/utils/Options.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/IntTypes.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Vec.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/XAlloc.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/utils/ParseUtils.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/utils/System.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/core/Solver.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Heap.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Alg.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/core/SolverTypes.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Map.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Alloc.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/core/BoundedQueue.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/core/Constants.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Clone.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/core/SolverStats.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/MaxSAT.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/MaxSATFormula.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/FormulaPB.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/MaxTypes.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/ParserMaxSAT.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/ParserPB.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/algorithms/Alg_LinearSU.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/algorithms/../Encoder.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/algorithms/../MaxTypes.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/algorithms/../encodings/Enc_CNetworks.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/algorithms/../encodings/Encodings.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/algorithms/../encodings/../MaxTypes.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/algorithms/../encodings/Enc_GTE.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/algorithms/../encodings/Enc_Ladder.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/algorithms/../encodings/Enc_MTotalizer.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/algorithms/../encodings/Enc_SWC.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/algorithms/../encodings/Enc_Totalizer.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/algorithms/../encodings/Enc_Adder.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/algorithms/../MaxSAT.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/algorithms/Alg_MSU3.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/algorithms/Alg_OLL.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/algorithms/Alg_PartMSU3.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/algorithms/../MaxSAT_Partition.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/algorithms/../MaxSAT.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/algorithms/../graph/Graph.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/algorithms/../graph/Graph_Communities.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/algorithms/../graph/Graph.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/algorithms/Alg_WBO.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/algorithms/../MaxTypes.h
/home/josalhor/Desktop/wbo-py/open-wbo/MaxSAT.o /home/josalhor/Desktop/wbo-py/open-wbo/MaxSAT.or /home/josalhor/Desktop/wbo-py/open-wbo/MaxSAT.od /home/josalhor/Desktop/wbo-py/open-wbo/MaxSAT.op: /home/josalhor/Desktop/wbo-py/open-wbo/MaxSAT.cc \
 /home/josalhor/Desktop/wbo-py/open-wbo/MaxSAT.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/core/Solver.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Heap.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Vec.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/IntTypes.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/XAlloc.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Alg.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/utils/Options.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/utils/ParseUtils.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/core/SolverTypes.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Map.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Alloc.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/core/BoundedQueue.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/core/Constants.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Clone.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/core/SolverStats.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/MaxSATFormula.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/FormulaPB.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/MaxTypes.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/utils/System.h
/home/josalhor/Desktop/wbo-py/open-wbo/MaxSATFormula.o /home/josalhor/Desktop/wbo-py/open-wbo/MaxSATFormula.or /home/josalhor/Desktop/wbo-py/open-wbo/MaxSATFormula.od /home/josalhor/Desktop/wbo-py/open-wbo/MaxSATFormula.op: /home/josalhor/Desktop/wbo-py/open-wbo/MaxSATFormula.cc \
 /home/josalhor/Desktop/wbo-py/open-wbo/MaxSATFormula.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/core/Solver.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Heap.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Vec.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/IntTypes.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/XAlloc.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Alg.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/utils/Options.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/utils/ParseUtils.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/core/SolverTypes.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Map.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Alloc.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/core/BoundedQueue.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/core/Constants.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Clone.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/core/SolverStats.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/FormulaPB.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/MaxTypes.h
/home/josalhor/Desktop/wbo-py/open-wbo/MaxSAT_Partition.o /home/josalhor/Desktop/wbo-py/open-wbo/MaxSAT_Partition.or /home/josalhor/Desktop/wbo-py/open-wbo/MaxSAT_Partition.od /home/josalhor/Desktop/wbo-py/open-wbo/MaxSAT_Partition.op: \
 /home/josalhor/Desktop/wbo-py/open-wbo/MaxSAT_Partition.cc \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/core/SolverTypes.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/IntTypes.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Alg.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Vec.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/XAlloc.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Map.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Alloc.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/MaxSAT_Partition.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/MaxSAT.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/core/Solver.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Heap.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/utils/Options.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/utils/ParseUtils.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/core/BoundedQueue.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/core/Constants.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Clone.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/core/SolverStats.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/MaxSATFormula.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/FormulaPB.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/MaxTypes.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/utils/System.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/graph/Graph.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/graph/Graph_Communities.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/graph/Graph.h
/home/josalhor/Desktop/wbo-py/open-wbo/ParserPB.o /home/josalhor/Desktop/wbo-py/open-wbo/ParserPB.or /home/josalhor/Desktop/wbo-py/open-wbo/ParserPB.od /home/josalhor/Desktop/wbo-py/open-wbo/ParserPB.op: /home/josalhor/Desktop/wbo-py/open-wbo/ParserPB.cc \
 /home/josalhor/Desktop/wbo-py/open-wbo/ParserPB.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/MaxSATFormula.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/core/Solver.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Heap.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Vec.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/IntTypes.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/XAlloc.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Alg.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/utils/Options.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/utils/ParseUtils.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/core/SolverTypes.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Map.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Alloc.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/core/BoundedQueue.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/core/Constants.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/mtl/Clone.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/solvers/glucose4.1/core/SolverStats.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/FormulaPB.h \
 /home/josalhor/Desktop/wbo-py/open-wbo/MaxTypes.h
