### Aperture Solver Configuration File

## External Options

# Solver: Topor, CaDiCaL, Glucose
solver=glucose

# Mode: ACNF, WCNF
mode=wcnf

## Solver Options

verbosity=3
output-coloring=true
strict-user-vars=false

# SAT-based optimization solving options

[opti]
use-initial-solver=false
# Different initial solver: Topor, CaDiCaL, Glucose, Kissat
initial-solver=kissat
use-complete-solver=true
complete-solver=cadical
conflict-threshold=10000000
polosat-max-epochs=1000000
polosat-update-bits-on-each-sat-model=true
polosat-weighted-obv-strategy=false
solve-optimistically=true
solve-conservatively=true
use-target-bumping=false
max-bump-rand-val=552
target-bump-score-value=50

[maxsat]
use-local-search=true
local-search-solver-type=band
disable-polosat=false
use-polosat-props-per-model-threshold=true
max-props-per-model=1000000
use-polosat-model-per-sec-threshold=false
min-models-per-sec=2.5

# MaxSAT solving options - MRS-Beaver options
mrs-beaver-max-iterations=2147483647
mrs-beaver-seed=1971603567
mrs-beaver-obv-conflict-threshold=1000
mrs-beaver-use-complete-part-solver=false
# Different complete part solver: Topor, CaDiCaL, Glucose
mrs-beaver-complete-part-solver=cadical
mrs-beaver-size-switch-to-complete=1000000